FROM node:22-bookworm

ARG USERNAME=vscode

RUN apt-get update && apt-get install -y --no-install-recommends nano \
      git curl sudo ca-certificates bash gnupg2 && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd $USERNAME && \
    useradd -m -g $USERNAME -s /bin/bash $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

COPY start.sh /start.sh
RUN chmod +x /start.sh

RUN npm install -g npm@11.4.0 \
  && npm install -g @angular/cli@19.2.13 \
  && npm cache clean --force

ENV NG_CLI_ANALYTICS=false
USER $USERNAME
WORKDIR /workspace

ENTRYPOINT ["sh", "/start.sh"]
