services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    ports:
      - "4200:4200"
    command: sleep infinity  
    depends_on:
      - sqlserver
      - apibackend
    environment:
      - DATABASE_HOST=mssql
      - DATABASE_PORT=1433
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=YourStrong!Passw0rd

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # container_name: sqlserver_dev
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  apibackend:
    build:
      context: .                          # contexto do repositório todo
      dockerfile: Dockerfile.backend
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:sqlserver://sqlserver:1433;encrypt=false",
          "spring.datasource.username": "SA",
          "spring.datasource.password": "YourStrong!Passw0rd"
        }
    ports:
      - "8080:8080"
    volumes:
      - ./spring-boot-run.sh:/spring-boot-run.sh
    command: /spring-boot-run.sh
    depends_on:
      - sqlserver

volumes:
  sqlserver_data: